site_name: Dev Notes
site_url: https://lcsgborges.github.io/dev-notes/
repo_name: dev-notes
repo_url: https://github.com/lcsgborges/dev-notes
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  language: pt-BR
  palette:
    scheme: default
    primary: blue grey
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
nav:
  - Home: index.md
  - Linguagens:
    - C:
      - OpenMP: c/openmp.md
    - Go:
      - Primeiros Passos: go/go.md
      - Exercícios: go/exercicios_basicos_go.md
    - Java: 
      - Primeiros Passos: java/java.md
      - Exercícios: java/exercicios_basicos.md
    - Python:
      - Alembic: python/alembic.md
      - Pillow: python/pillow.md
      - SQLAlchemy: python/sqlalchemy.md
      - Type Hints: python/types-hints-py.md
  - Devops:
    - Docker: devops/docker.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format